apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: success-rate
    interval: 1m
    successCondition: "len(result[0].Values) >= 5 and all(result[0].Values, {# <= 0.01})"
    failureLimit: 3
    provider:
      cloudWatch:
        interval: 30m
        metricDataQueries:
        - {
            "id": "rate",
            "expression": "errors / requests"
          }
        - {
            "id": "errors",
            "metricStat": {
              "metric": {
                "namespace": "app",
                "metricName": "errors"
              },
              "period": 300,
              "stat": "Sum",
              "unit": "Count"
            },
            "returnData": false
          }
        - {
            "id": "requests",
            "metricStat": {
              "metric": {
                "namespace": "app",
                "metricName": "requests"
              },
              "period": 300,
              "stat": "Sum",
              "unit": "Count"
            },
            "returnData": false
          }
