apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: success-rate
    interval: 1m
    successCondition: "all(result[0].Values, {# <= 0.01})"
    failureLimit: 3
    provider:
      cloudWatch:
        interval: 5m
        metricDataQueries:
        - {
            "id": "rate",
            "expression": "errors / requests"
          }
        - {
            "id": "errors",
            "metricStat": {
              "metric": {
                "namespace": "AWS/ApplicationELB",
                "metricName": "HTTPCode_Target_5XX_Count",
                "dimensions": [
                  {
                    "name": "LoadBalancer",
                    "value": "app/k8s-testapp-canaryde-0f7124f27b/1a76aa256a0e5306"
                  }
                ]
              },
              "period": 30,
              "stat": "Sum",
              "unit": "Count"
            },
            "returnData": true
          }
        - {
            "id": "requests",
            "metricStat": {
              "metric": {
                "namespace": "AWS/ApplicationELB",
                "metricName": "HTTPCode_Target_2XX_Count",
                "dimensions": [
                  {
                    "name": "LoadBalancer",
                    "value": "app/k8s-testapp-canaryde-0f7124f27b/1a76aa256a0e5306"
                  }
                ]
              },
              "period": 30,
              "stat": "Sum",
              "unit": "Count"
            },
            "returnData": true
          }
