apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: canary-demo-preview
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    ingress.kubernetes.io/app-root: /
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: canary-demo-preview
            servicePort: 80