apiVersion: batch/v1
kind: Job
metadata:
  generateName: aws-demo-promote-prod-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: aws-demo-promote-prod
        image: 985266629220.dkr.ecr.eu-west-1.amazonaws.com/gitops:0.02
        env:
          - name: GIT_USER
            valueFrom:
              secretKeyRef:
                name: aws-codecommit
                key: username
          - name: GIT_PASS
            valueFrom:
              secretKeyRef:
                name: aws-codecommit
                key: password
          - name: GIT_MAIL
            value: argocd@aws.com
          - name: GIT_USERNAME
            value: ArgoCD
          - name: GIT_REPO
            value: git-codecommit.eu-west-1.amazonaws.com/v1/repos/aws-demo-app-deploy
          - name: GIT_BRANCH
            value: prod
          - name: GIT_MESSAGE
            value: update version
          - name: SED_IMAGE
            value: "985266629220.dkr.ecr.eu-west-1.amazonaws.com/aws-demo"
          - name: SED_TAG
            value: d438b07e
          - name: SED_FILE
            value: ./canary/canary-rollout.yaml
      restartPolicy: Never
  backoffLimit: 2